"""
Write a Python program to calculate sales from the current day's orders
generated by your ice cream shop program.  Use the following values to calculate
the cost of an order:
Cup = 1.00
Cone = 1.50
Scoop = 1.50

Print out the sales amount for each order and finally print the total sales amount for the day.
"""

# Import modules to get current date and process JSON objects
from datetime import datetime
import json

# Assign values from price list
cup_cost = 1.00
cone_cost = 1.50
scoop_cost = 1.50

# Programmatically create file name
today = datetime.now()
orders_file_name = today.strftime("orders_%Y%m%d.txt")

# Initialize a list to hold data from the file 
orders = []

# open the file in read mode
f = open(orders_file_name, "r")

# Loop through the file to convert JSON objects to dicts
# Add each dict to the list
for line in f:
    order = json.loads(line)
    orders.append(order)
# Close the file after reading
f.close()
        
# Initialize variable for the total sales of the day
total_sales = 0

# Loop through the list of dicts
for o in orders:
    # Initialize variable to hold each order's total
    sales = 0
    
    # Loop through the dictionary to find container type and number of scoops
    # Calculate and store totals
    for item in o:
        if item['container'] == "cup":
            sales += cup_cost
        else:
            sales += cone_cost
            
        num_scoops = len(item["scoops"])
        
        sales += num_scoops * scoop_cost
        total_sales += sales
        
    print(f"Total for order: {sales}")
        

print(f"Total Sales: {total_sales}")
        
